TOTAL_FRAMES = 5*200000
EPS_ANNEALING_FRAMES = TOTAL_FRAMES / 4
MIN_REPLAY_BUFFER_SIZE = 1250
# LEARNING_RATE = 2.5e-4
LEARNING_RATE = 0.001
MEM_SIZE = int(TOTAL_FRAMES / 10)
BATCH_SIZE = 8
UPDATE_FREQ = 4
TARGET_UPDATE_FREQ = 100
DISCOUNT_FACTOR = 0.99
PRIORITY_SCALE = 0.7

SAVE_FRAMES = False
SAVE_PATH='data'

USE_PER = True

RENDER_TRAINING = False

HISTORY_LENGTH = 4

SHARE_EXP_FREQ = 100

DECAY_STEPS=TOTAL_FRAMES/200
DECAY_RATE=0.96
